# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull requests
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, self-hosted-utvikling-1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - uses: actions/checkout@v2
    
    #- name: Deploy ARM Template
    #  uses: azure/CLI@v1
      #with:
        #inlineScript: |
            #  az login --identity
            #  az account set --subscription a4bf7b1d-dc1f-491a-9330-2c7092e7d20e
            #  az deployment group create --resource-group myResourceGroupLink --template-file ./chaintemplate.json --debug --parameters projectName=link1 linkedTemplateUri='https://sentralrepo.blob.core.windows.net/templatestore/sa-armtemplate.json'
    
    - name: Deploy ARM Template
      run:
        |    
        pwsh ./deploy.ps1


